-- Database: techmate

-- DROP DATABASE IF EXISTS techmate;
-- Primero crear la base de datos techmate
CREATE DATABASE techmate
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Peru.1252'
    LC_CTYPE = 'Spanish_Peru.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


-- segundo ejecutar el script de la creacion de los tipos enum
-- 1. Tipo para Roles de Usuario
CREATE TYPE user_role AS ENUM ('Cliente', 'Agente', 'Admin');

-- 2. Tipo para Estado de Pedido
CREATE TYPE order_status AS ENUM ('Pendiente', 'Procesando', 'Enviado', 'Entregado', 'Cancelado');

-- 3. Tipo para Método de Pago
CREATE TYPE payment_method AS ENUM ('Tarjeta', 'PayPal', 'Transferencia');

-- 4. Tipo para Estado de Pago
CREATE TYPE payment_status AS ENUM ('Pendiente', 'Aprobado', 'Rechazado', 'Reembolsado');

-- 5. Tipo para Estado de Devolución
CREATE TYPE return_status AS ENUM ('Solicitada', 'Aprobada', 'Rechazada', 'Completada');

-- 6. Tipo para Estado de Reseña
CREATE TYPE review_status AS ENUM ('Pendiente', 'Aprobada', 'Rechazada');

-- 7. Tipo para Tipo de Descuento
CREATE TYPE discount_type AS ENUM ('Porcentaje', 'Monto_Fijo');

-- 8. Tipo para Prioridad de Ticket
CREATE TYPE ticket_priority AS ENUM ('Baja', 'Media', 'Alta', 'Urgente');

-- 9. Tipo para Estado de Ticket
CREATE TYPE ticket_status AS ENUM ('Abierto', 'En_Proceso', 'Resuelto', 'Cerrado');

-- 10. Tipo para Movimiento de Inventario
CREATE TYPE inventory_movement_type AS ENUM ('Entrada', 'Salida', 'Ajuste_Positivo', 'Ajuste_Negativo', 'Devolucion_Cliente');


-- por último ejecutar el script para la creación de tablas
CREATE TABLE "USUARIOS" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "fecha_registro" date NOT NULL DEFAULT (CURRENT_DATE),
  "rol" user_role NOT NULL DEFAULT 'Cliente',
  "activo" boolean NOT NULL DEFAULT true,
  "ultima_sesion" timestamp,
  "url_img" varchar(255)
);

CREATE TABLE "DIRECCIONES" (
  "id_direccion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int NOT NULL,
  "calle" varchar(255) NOT NULL,
  "ciudad" varchar(100) NOT NULL,
  "estado" varchar(100) NOT NULL,
  "codigo_postal" varchar(20) NOT NULL,
  "pais" varchar(100) NOT NULL DEFAULT 'Perú',
  "es_principal" boolean DEFAULT false,
  "nombre_direccion" varchar(100)
);

CREATE TABLE "CATEGORIAS" (
  "id_categoria" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "descripcion" text,
  "categoria_padre" int,
  "activa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "PRODUCTOS" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_categoria" int NOT NULL,
  "nombre" varchar(200) NOT NULL,
  "descripcion" text,
  "precio" decimal(10,2) NOT NULL,
  "stock" int NOT NULL DEFAULT 0,
  "sku" varchar(50) UNIQUE NOT NULL,
  "marca" varchar(100),
  "especificaciones" text,
  "calificacion_promedio" decimal(2,1) DEFAULT 0,
  "total_resenas" int DEFAULT 0,
  "activo" boolean NOT NULL DEFAULT true,
  "fecha_creacion" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "INVENTARIO" (
  "id_inventario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int UNIQUE NOT NULL,
  "cantidad_disponible" int NOT NULL,
  "cantidad_reservada" int NOT NULL DEFAULT 0,
  "stock_minimo" int NOT NULL,
  "ultima_actualizacion" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "MOVIMIENTOS_INVENTARIO" (
  "id_movimiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "tipo_movimiento" inventory_movement_type not null,
  "cantidad" int NOT NULL,
  "fecha_movimiento" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "id_usuario_registro" int NOT NULL,
  "referencia_externa" varchar(100)
);

CREATE TABLE "IMAGENES_PRODUCTO" (
  "id_imagen" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "url_imagen" varchar(500) NOT NULL,
  "es_principal" boolean DEFAULT false,
  "orden" int DEFAULT 0
);

CREATE TABLE "CARRITO" (
  "id_carrito" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int NOT NULL,
  "id_producto" int NOT NULL,
  "cantidad" int NOT NULL DEFAULT 1,
  "fecha_agregado" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "LISTA_DESEOS" (
  "id_lista" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int NOT NULL,
  "id_producto" int NOT NULL,
  "fecha_agregado" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "PEDIDOS" (
  "id_pedido" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int NOT NULL,
  "id_direccion" int NOT NULL,
  "subtotal" decimal(10,2) NOT NULL,
  "impuestos" decimal(10,2) NOT NULL,
  "total" decimal(10,2) NOT NULL,
  "estado" order_status NOT NULL DEFAULT 'Pendiente',
  "fecha_pedido" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "fecha_entrega" timestamp,
  "notas" text
);

CREATE TABLE "DETALLE_PEDIDO" (
  "id_detalle" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_pedido" int NOT NULL,
  "id_producto" int NOT NULL,
  "cantidad" int NOT NULL,
  "precio_unitario" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL
);

CREATE TABLE "PAGOS" (
  "id_pago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_pedido" int UNIQUE NOT NULL,
  "metodo_pago" payment_method NOT NULL,
  "monto" decimal(10,2) NOT NULL,
  "estado" payment_status NOT NULL DEFAULT 'Pendiente',
  "transaccion_id" varchar(100) UNIQUE,
  "fecha_pago" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "DEVOLUCIONES" (
  "id_devolucion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_pedido" int NOT NULL,
  "motivo" text NOT NULL,
  "estado" return_status NOT NULL DEFAULT 'Solicitada',
  "monto_reembolso" decimal(10,2),
  "fecha_solicitud" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "fecha_resolucion" timestamp
);

CREATE TABLE "RESENAS" (
  "id_resena" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "id_usuario" int NOT NULL,
  "id_pedido" int NOT NULL,
  "calificacion" int NOT NULL,
  "titulo" varchar(200),
  "comentario" text,
  "compra_verificada" boolean NOT NULL DEFAULT true,
  "votos_utiles" int DEFAULT 0,
  "votos_no_utiles" int DEFAULT 0,
  "estado" review_status NOT NULL DEFAULT 'Pendiente',
  "fecha_publicacion" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "fecha_moderacion" timestamp
);

CREATE TABLE "IMAGENES_RESENA" (
  "id_imagen_resena" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_resena" int NOT NULL,
  "url_imagen" varchar(500) NOT NULL,
  "orden" int DEFAULT 0
);

CREATE TABLE "VALORACIONES_RESENA" (
  "id_valoracion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_resena" int NOT NULL,
  "id_usuario" int NOT NULL,
  "es_util" boolean NOT NULL,
  "fecha_valoracion" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "PROMOCIONES" (
  "id_promocion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(50) UNIQUE NOT NULL,
  "descripcion" text,
  "tipo_descuento" discount_type NOT NULL,
  "valor_descuento" decimal(10,2) NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date NOT NULL,
  "usos_maximos" int,
  "usos_actuales" int DEFAULT 0,
  "activa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "PRODUCTOS_PROMOCIONES" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "id_promocion" int NOT NULL
);

CREATE TABLE "TICKETS_SOPORTE" (
  "id_ticket" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int NOT NULL,
  "id_pedido" int,
  "asunto" varchar(255) NOT NULL,
  "descripcion" text NOT NULL,
  "prioridad" ticket_priority NOT NULL DEFAULT 'Media',
  "estado" ticket_status NOT NULL DEFAULT 'Abierto',
  "id_agente_asignado" int,
  "fecha_creacion" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "fecha_actualizacion" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "MENSAJES_TICKET" (
  "id_mensaje" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_ticket" int NOT NULL,
  "id_usuario" int NOT NULL,
  "mensaje" text NOT NULL,
  "es_agente" boolean NOT NULL DEFAULT false,
  "fecha_envio" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "FAQS" (
  "id_faq" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pregunta" varchar(500) NOT NULL,
  "respuesta" text NOT NULL,
  "id_categoria" int,
  "orden" int DEFAULT 0,
  "activa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "LOGS_SISTEMA" (
  "id_log" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" int,
  "accion" varchar(100) NOT NULL,
  "descripcion" text,
  "ip_address" varchar(45),
  "fecha_hora" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "HISTORIAL_PRECIOS" (
  "id_registro" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" int NOT NULL,
  "precio_anterior" decimal(10,2),
  "precio_nuevo" decimal(10,2) NOT NULL,
  "fecha_inicio" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "id_usuario_cambio" int
);

CREATE INDEX ON "USUARIOS" ("email");

CREATE INDEX ON "USUARIOS" ("rol");

CREATE INDEX ON "DIRECCIONES" ("id_usuario");

CREATE INDEX ON "CATEGORIAS" ("nombre");

CREATE INDEX ON "CATEGORIAS" ("categoria_padre");

CREATE INDEX ON "PRODUCTOS" ("id_categoria");

CREATE INDEX ON "PRODUCTOS" ("sku");

CREATE INDEX ON "PRODUCTOS" ("marca");

CREATE INDEX ON "PRODUCTOS" ("activo");

CREATE INDEX ON "PRODUCTOS" ("calificacion_promedio");

CREATE INDEX ON "INVENTARIO" ("id_producto");

CREATE INDEX ON "MOVIMIENTOS_INVENTARIO" ("id_producto");

CREATE INDEX ON "MOVIMIENTOS_INVENTARIO" ("tipo_movimiento");

CREATE INDEX ON "MOVIMIENTOS_INVENTARIO" ("fecha_movimiento");

CREATE INDEX ON "IMAGENES_PRODUCTO" ("id_producto");

CREATE INDEX ON "IMAGENES_PRODUCTO" ("es_principal");

CREATE UNIQUE INDEX ON "CARRITO" ("id_usuario", "id_producto");

CREATE INDEX ON "CARRITO" ("id_usuario");

CREATE INDEX ON "CARRITO" ("id_producto");

CREATE UNIQUE INDEX ON "LISTA_DESEOS" ("id_usuario", "id_producto");

CREATE INDEX ON "LISTA_DESEOS" ("id_usuario");

CREATE INDEX ON "LISTA_DESEOS" ("id_producto");

CREATE INDEX ON "PEDIDOS" ("id_usuario");

CREATE INDEX ON "PEDIDOS" ("estado");

CREATE INDEX ON "PEDIDOS" ("fecha_pedido");

CREATE INDEX ON "DETALLE_PEDIDO" ("id_pedido");

CREATE INDEX ON "DETALLE_PEDIDO" ("id_producto");

CREATE INDEX ON "PAGOS" ("id_pedido");

CREATE INDEX ON "PAGOS" ("estado");

CREATE INDEX ON "PAGOS" ("transaccion_id");

CREATE INDEX ON "DEVOLUCIONES" ("id_pedido");

CREATE INDEX ON "DEVOLUCIONES" ("estado");

CREATE INDEX ON "RESENAS" ("id_producto");

CREATE INDEX ON "RESENAS" ("id_usuario");

CREATE INDEX ON "RESENAS" ("id_pedido");

CREATE INDEX ON "RESENAS" ("estado");

CREATE INDEX ON "RESENAS" ("calificacion");

CREATE UNIQUE INDEX ON "RESENAS" ("id_usuario", "id_producto", "id_pedido");

CREATE INDEX ON "IMAGENES_RESENA" ("id_resena");

CREATE UNIQUE INDEX ON "VALORACIONES_RESENA" ("id_resena", "id_usuario");

CREATE INDEX ON "VALORACIONES_RESENA" ("id_resena");

CREATE INDEX ON "VALORACIONES_RESENA" ("id_usuario");

CREATE INDEX ON "PROMOCIONES" ("codigo");

CREATE INDEX ON "PROMOCIONES" ("activa");

CREATE INDEX ON "PROMOCIONES" ("fecha_inicio");

CREATE INDEX ON "PROMOCIONES" ("fecha_fin");

CREATE UNIQUE INDEX ON "PRODUCTOS_PROMOCIONES" ("id_producto", "id_promocion");

CREATE INDEX ON "TICKETS_SOPORTE" ("id_usuario");

CREATE INDEX ON "TICKETS_SOPORTE" ("id_agente_asignado");

CREATE INDEX ON "TICKETS_SOPORTE" ("estado");

CREATE INDEX ON "TICKETS_SOPORTE" ("prioridad");

CREATE INDEX ON "MENSAJES_TICKET" ("id_ticket");

CREATE INDEX ON "MENSAJES_TICKET" ("fecha_envio");

CREATE INDEX ON "FAQS" ("id_categoria");

CREATE INDEX ON "FAQS" ("activa");

CREATE INDEX ON "FAQS" ("orden");

CREATE INDEX ON "LOGS_SISTEMA" ("id_usuario");

CREATE INDEX ON "LOGS_SISTEMA" ("accion");

CREATE INDEX ON "LOGS_SISTEMA" ("fecha_hora");

CREATE INDEX ON "HISTORIAL_PRECIOS" ("id_producto");

CREATE INDEX ON "HISTORIAL_PRECIOS" ("fecha_inicio");

COMMENT ON COLUMN "INVENTARIO"."cantidad_disponible" IS 'Stock listo para vender';

COMMENT ON COLUMN "INVENTARIO"."cantidad_reservada" IS 'Stock asignado a pedidos pendientes de envio';

COMMENT ON COLUMN "INVENTARIO"."stock_minimo" IS 'Punto de reorden';

COMMENT ON COLUMN "MOVIMIENTOS_INVENTARIO"."tipo_movimiento" IS 'Entrada=Recepcion, Salida=Venta';

COMMENT ON COLUMN "MOVIMIENTOS_INVENTARIO"."cantidad" IS 'Cantidad movida (siempre positiva)';

COMMENT ON COLUMN "MOVIMIENTOS_INVENTARIO"."id_usuario_registro" IS 'Admin/Agente que registra';

COMMENT ON COLUMN "MOVIMIENTOS_INVENTARIO"."referencia_externa" IS 'Ej. Número de Guía de Remisión o Factura del Proveedor';

COMMENT ON COLUMN "RESENAS"."calificacion" IS '1-5 estrellas';

COMMENT ON COLUMN "HISTORIAL_PRECIOS"."fecha_inicio" IS 'Fecha en que el precio entró en vigor';

ALTER TABLE "DIRECCIONES" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "CATEGORIAS" ADD FOREIGN KEY ("categoria_padre") REFERENCES "CATEGORIAS" ("id_categoria");

ALTER TABLE "PRODUCTOS" ADD FOREIGN KEY ("id_categoria") REFERENCES "CATEGORIAS" ("id_categoria");

ALTER TABLE "INVENTARIO" ADD FOREIGN KEY ("id_producto") REFERENCES "PRODUCTOS" ("id_producto");

ALTER TABLE "MOVIMIENTOS_INVENTARIO" ADD FOREIGN KEY ("id_producto") REFERENCES "PRODUCTOS" ("id_producto");

ALTER TABLE "MOVIMIENTOS_INVENTARIO" ADD FOREIGN KEY ("id_usuario_registro") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "IMAGENES_PRODUCTO" ADD FOREIGN KEY ("id_producto") REFERENCES "PRODUCTOS" ("id_producto");

ALTER TABLE "CARRITO" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "CARRITO" ADD FOREIGN KEY ("id_producto") REFERENCES "PRODUCTOS" ("id_producto");

ALTER TABLE "LISTA_DESEOS" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "LISTA_DESEOS" ADD FOREIGN KEY ("id_producto") REFERENCES "PRODUCTOS" ("id_producto");

ALTER TABLE "PEDIDOS" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "PEDIDOS" ADD FOREIGN KEY ("id_direccion") REFERENCES "DIRECCIONES" ("id_direccion");

ALTER TABLE "DETALLE_PEDIDO" ADD FOREIGN KEY ("id_pedido") REFERENCES "PEDIDOS" ("id_pedido");

ALTER TABLE "DETALLE_PEDIDO" ADD FOREIGN KEY ("id_producto") REFERENCES "PRODUCTOS" ("id_producto");

ALTER TABLE "PAGOS" ADD FOREIGN KEY ("id_pedido") REFERENCES "PEDIDOS" ("id_pedido");

ALTER TABLE "DEVOLUCIONES" ADD FOREIGN KEY ("id_pedido") REFERENCES "PEDIDOS" ("id_pedido");

ALTER TABLE "RESENAS" ADD FOREIGN KEY ("id_producto") REFERENCES "PRODUCTOS" ("id_producto");

ALTER TABLE "RESENAS" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "RESENAS" ADD FOREIGN KEY ("id_pedido") REFERENCES "PEDIDOS" ("id_pedido");

ALTER TABLE "IMAGENES_RESENA" ADD FOREIGN KEY ("id_resena") REFERENCES "RESENAS" ("id_resena");

ALTER TABLE "VALORACIONES_RESENA" ADD FOREIGN KEY ("id_resena") REFERENCES "RESENAS" ("id_resena");

ALTER TABLE "VALORACIONES_RESENA" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "PRODUCTOS_PROMOCIONES" ADD FOREIGN KEY ("id_producto") REFERENCES "PRODUCTOS" ("id_producto");

ALTER TABLE "PRODUCTOS_PROMOCIONES" ADD FOREIGN KEY ("id_promocion") REFERENCES "PROMOCIONES" ("id_promocion");

ALTER TABLE "TICKETS_SOPORTE" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "TICKETS_SOPORTE" ADD FOREIGN KEY ("id_pedido") REFERENCES "PEDIDOS" ("id_pedido");

ALTER TABLE "TICKETS_SOPORTE" ADD FOREIGN KEY ("id_agente_asignado") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "MENSAJES_TICKET" ADD FOREIGN KEY ("id_ticket") REFERENCES "TICKETS_SOPORTE" ("id_ticket");

ALTER TABLE "MENSAJES_TICKET" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "FAQS" ADD FOREIGN KEY ("id_categoria") REFERENCES "CATEGORIAS" ("id_categoria");

ALTER TABLE "LOGS_SISTEMA" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIOS" ("id_usuario");

ALTER TABLE "HISTORIAL_PRECIOS" ADD FOREIGN KEY ("id_producto") REFERENCES "PRODUCTOS" ("id_producto");

ALTER TABLE "HISTORIAL_PRECIOS" ADD FOREIGN KEY ("id_usuario_cambio") REFERENCES "USUARIOS" ("id_usuario");
